apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedular
  namespace: cronjob
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi